"""Phase 4 render: hand assets to the Remotion service and wait for the mp4.

  render_video(video_id) -> POST <RENDER_SERVICE_URL>/render with all assets
                            (signed S3 URLs, scene metadata, captions JSON,
                            CTA), then on success:
                              - store result.s3_key on Video.s3_key_mp4
                              - record a render cost_event
                              - check_video_cap (might raise CostCapExceeded)
                              - transition pending_render -> pending_review

Idempotent on Video.status: re-running once the video is past pending_render
(approved / publishing / published) returns immediately without calling
the render service.
"""

from __future__ import annotations

from decimal import Decimal
from typing import Any
from uuid import UUID

import httpx
from celery import shared_task
from celery.utils.log import get_task_logger
from sqlalchemy import select

from shortstack_core.cost import (
    CostCapExceeded,
    check_video_cap,
    record_cost,
)
from shortstack_core.db import Asset, Niche, Script, Video, session_scope
from shortstack_core.enums import AssetKind, CostKind, VideoStatus
from shortstack_core.schemas import CaptionsDoc, ScriptDraft
from shortstack_core.settings import get_settings
from shortstack_core.storage import download_bytes, signed_url

from ..celery_app import app  # noqa: F401  (ensures app is registered)

log = get_task_logger(__name__)

# Estimated CPU cost on the worker box. Tunable; tracked in DECISIONS.md.
RENDER_COST_PER_SEC_USD = 0.001

# Signed-URL TTL handed to Remotion. 1h is plenty for a single render.
SIGNED_URL_TTL_SEC = 3600


def _build_render_request(
    *,
    video_id: str,
    draft: ScriptDraft,
    scene_image_keys: dict[int, str],
    audio_key: str,
    captions: CaptionsDoc,
) -> dict[str, Any]:
    """Pure helper: assemble the body POSTed to the render service.

    Extracted so it can be unit-tested without S3 / DB / network.
    Signed URLs are generated by the caller and passed in via ``scene_image_keys``
    + ``audio_key`` (well, those are S3 keys; the caller can pass already-signed
    URLs or call ``signed_url`` themselves -- we keep it as a key here for test
    determinism).
    """
    return {
        "video_id": video_id,
        "scenes": [
            {
                "index": s.index,
                "image_url": signed_url(
                    scene_image_keys[s.index], ttl_sec=SIGNED_URL_TTL_SEC
                ),
                "duration_sec": float(s.duration_sec),
                "narration": s.narration,
                "on_screen_text": s.on_screen_text,
            }
            for s in draft.scenes
        ],
        "audio_url": signed_url(audio_key, ttl_sec=SIGNED_URL_TTL_SEC),
        "captions": [w.model_dump() for w in captions.words],
        "cta": draft.cta,
        "total_duration_sec": float(draft.total_duration_sec),
    }


@shared_task(
    name="shortstack_worker.tasks.render.render_video",
    autoretry_for=(httpx.HTTPError,),
    retry_backoff=True,
    retry_backoff_max=300,
    retry_jitter=True,
    max_retries=2,
    acks_late=True,
)
def render_video(video_id: str) -> dict[str, Any]:
    settings = get_settings()
    video_uuid = UUID(video_id)

    with session_scope() as s:
        video = s.get(Video, video_uuid)
        if video is None:
            raise ValueError(f"video {video_id} not found")
        if video.status != VideoStatus.PENDING_RENDER:
            log.info(
                "render_video.skip",
                extra={"video_id": video_id, "status": video.status.value},
            )
            return {
                "video_id": video_id,
                "status": video.status.value,
                "skipped": True,
            }
        script = s.get(Script, video.script_id)
        niche = s.get(Niche, video.niche_id)
        if script is None or niche is None:
            raise ValueError(f"missing script or niche for video {video_id}")
        draft = ScriptDraft.model_validate(script.draft_json)
        cost_cap = niche.cost_cap_cents
        niche_id = niche.id

        assets = (
            s.execute(select(Asset).where(Asset.script_id == script.id))
            .scalars()
            .all()
        )

        scene_images: dict[int, str] = {
            a.scene_index: a.s3_key
            for a in assets
            if a.kind == AssetKind.IMAGE and a.scene_index is not None
        }
        audio = next(
            (a for a in assets if a.kind == AssetKind.AUDIO_VOICE), None
        )
        captions_asset = next(
            (a for a in assets if a.kind == AssetKind.CAPTIONS_JSON), None
        )

        if audio is None:
            raise ValueError(f"video {video_id} missing audio_voice asset")
        if captions_asset is None:
            raise ValueError(f"video {video_id} missing captions_json asset")
        for scene in draft.scenes:
            if scene.index not in scene_images:
                raise ValueError(
                    f"video {video_id} missing image asset for scene {scene.index}"
                )

        captions_bytes = download_bytes(captions_asset.s3_key)
        captions_doc = CaptionsDoc.model_validate_json(captions_bytes)

        request_body = _build_render_request(
            video_id=video_id,
            draft=draft,
            scene_image_keys=scene_images,
            audio_key=audio.s3_key,
            captions=captions_doc,
        )

    # Heavy call outside the DB transaction.
    log.info(
        "render_video.calling",
        extra={"video_id": video_id, "url": settings.render_service_url},
    )
    with httpx.Client(timeout=600.0) as client:
        resp = client.post(
            f"{settings.render_service_url}/render",
            json=request_body,
        )
        resp.raise_for_status()
        result = resp.json()

    s3_key = result["s3_key"]
    render_ms = int(result.get("render_ms", 0))
    render_sec = render_ms / 1000.0
    cost_cents = Decimal(str(RENDER_COST_PER_SEC_USD * render_sec)) * Decimal("100")

    try:
        with session_scope() as s:
            video = s.get(Video, video_uuid)
            if video is None:
                raise ValueError(f"video {video_id} not found")
            record_cost(
                s,
                niche_id=niche_id,
                kind=CostKind.RENDER,
                provider="remotion",
                cost_cents=cost_cents,
                units=render_sec,
                video_id=video_uuid,
                meta={
                    "render_ms": render_ms,
                    "size_bytes": result.get("size_bytes"),
                },
            )
            check_video_cap(s, video_id=video_uuid, hard_cap_cents=cost_cap)
            video.s3_key_mp4 = s3_key
            video.duration_sec = Decimal(
                str(result.get("duration_sec", float(draft.total_duration_sec)))
            )
            video.status = VideoStatus.PENDING_REVIEW
    except CostCapExceeded:
        # Render already paid for; mark failed so we don't continue down the
        # pipeline, but keep the mp4 reference for forensics.
        with session_scope() as s:
            video = s.get(Video, video_uuid)
            if video is not None:
                video.s3_key_mp4 = s3_key
                video.status = VideoStatus.FAILED
                video.failure_reason = (
                    f"cost_cap (render pushed total over {cost_cap}c)"
                )
        raise

    log.info(
        "render_video.done",
        extra={
            "video_id": video_id,
            "s3_key": s3_key,
            "render_ms": render_ms,
            "cost_cents": float(cost_cents),
        },
    )
    return {
        "video_id": video_id,
        "s3_key_mp4": s3_key,
        "render_ms": render_ms,
        "render_cost_cents": float(cost_cents),
        "next_status": VideoStatus.PENDING_REVIEW.value,
    }
